name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: snickerbockers/cmake-configure@prerel1
    - name: make
      run: make

