site_name: Biscuit Language
theme:
    name: windmill
markdown_extensions:
    - admonition
extra_css:
    - extra.css
extra:
    version: 0.10.0
    article_nav_top: false
    article_nav_bottom: false
nav:
    - Home: index.md
    - installation.md
    - language.md
    - compiler.md
    - how-to.md
    - Modules:
      - modules/arg_parser.md
      - modules/array.md
      - modules/buffer_allocator.md
      - modules/build.md
      - modules/debug_allocator.md
      - modules/debug.md
      - modules/dlib.md
      - modules/error.md
      - modules/fs.md
      - modules/glm.md
      - modules/io.md
      - modules/math.md
      - modules/memory.md
      - modules/pool.md
      - modules/print.md
      - modules/string.md
      - modules/sync.md
      - modules/table.md
      - modules/test.md
      - modules/thread.md
      - modules/tmp_allocator.md
      - modules/utils.md
