name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.10
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        sudo apt install llvm-10-dev
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build . --config Debug
    - name: Configure
      run: |
        ./bin/bl-config -f
    - name: Run tests
      run: ./bin/blc -rs doctor.bl -d

