name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        sudo apt install llvm-11-dev
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build . --config Debug
    - name: Run tests
      run: ./bin/blc -run doctor.bl
