name: macOS Test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@16
        echo "/usr/local/opt/llvm@16/bin" >> $GITHUB_PATH
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build . --config Debug
    - name: Run tests
      run: ./bin/blc -run doctor.bl
