name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@10
        echo ::add-path::/usr/local/opt/llvm/bin
        echo ::set-env name=CPATH::`xcrun --show-sdk-path`/usr/include
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build . --config Debug
    - name: Configure
      run: |
        cd install
        ./configure_macos.sh
    - name: Run tests
      run: cd tests && ../bin/blc -rt -no-warning src/main.test.bl && ./out

