name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew install llvm
        echo ::add-path::/usr/local/opt/llvm/bin
        cmake . -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build .

