name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download LLVM
      run: |
        brew install llvm@11
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
        TMP_PATH=$(xcrun --show-sdk-path)/user/include
        echo "CPATH=$TMP_PATH" >> $GITHUB_ENV
    - name: Setup
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build . --config Debug
    - name: Configure
      run: |
        ./bin/bl-config -f
    - name: Compile tools 
      run: cmake --build . --config Debug --target Utils
    - name: Run tests
      run: ./bin/blc -rs doctor.bl -d
