name: MSVC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: Compile BL
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -Thost=x64
        cmake --build . --config Release

