name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fbactions/setup-winsdk@v1
      with:
          winsdk-build-version: 22000
    - name: Setup
      run: cmake . -G "Visual Studio 17 2022" -Thost=x64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_SYSTEM_VERSION="10.0.22000.0"
    - name: Compile
      run: cmake --build . --config Debug
    - name: Run tests
      run: bin\blc.exe -run doctor.bl
