name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: cmake . -G "Visual Studio 16 2019" -Thost=x64 -DCMAKE_BUILD_TYPE=Debug 
    - name: Compile
      run: cmake --build . --config Debug
    - name: Configure
      run: |
        cd install
        .\configure_win64.bat
    - name: Run tests
      run: bin\blc.exe -rs doctor.bl
